# .bash_aliases

# You may uncomment the following lines if you want `ls' to be colorized:
export LS_OPTIONS='--color=auto'
eval "$(dircolors)"
alias ls='ls $LS_OPTIONS'
alias ll='ls $LS_OPTIONS -l'
alias l='ls $LS_OPTIONS -lAFh'

alias grep='grep --color=auto'

alias myip='curl ifconfig.co/'

function ipa {
  curl -s https://ifconfig.co/json?ip=$1 | jq 'del(.user_agent)'
  }

function ipc {
  curl -s https://ifconfig.co/json?ip=$1 | jq '.country'
  }
